// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables - must be set in Railway or .env file
// These should be set in Railway frontend service Variables tab:
// - VITE_SUPABASE_URL
// - VITE_SUPABASE_PUBLISHABLE_KEY
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Check if Supabase is properly configured
const isSupabaseConfigured = SUPABASE_URL && 
                              SUPABASE_PUBLISHABLE_KEY && 
                              SUPABASE_URL !== '' && 
                              SUPABASE_PUBLISHABLE_KEY !== '' &&
                              !SUPABASE_URL.includes('placeholder') &&
                              !SUPABASE_PUBLISHABLE_KEY.includes('placeholder');

// Create client only if environment variables are provided
// If not set, create a mock client that fails gracefully
export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : ({
      from: () => ({
        insert: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured' } }),
        select: () => Promise.resolve({ data: [], error: { message: 'Supabase not configured' } }),
        delete: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured' } }),
      }),
      functions: {
        invoke: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured' } }),
      },
    } as any);